version: 2.1
orbs:
  codecov: codecov/codecov@3.2.2

jobs:
  full-build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
          
      - run:
          name: Test
          command: mvn test
          
      - store_artifacts:
          path:  target
          
      - store_test_results:
          path: target/surefire-reports
          
      - codecov/upload:
          file: target/coverage-reports/jacoco.xml
          
workflows:
  full-build:
    jobs:
      - full-build
